*** Create strategies and look for parallel actions

(smod CO-SIMULATION-STRAT is
  protecting COSIMULATION .

  strat fmi_rules_setExpt @ GlobalState .

  vars M1 M2 : SUID .
  var FS : fmiState .
  var  S : GlobalState .

  sd fmi_rules_setExpt := 
     (matchrew S s.t. < M1 : SU | state : Instantiated > /\ < M2 : SU | state : FS > /\ FS =/= Instantiated  by
              S using setExp[ID1 <- M1] 
     ) ! .


endsm)